Connect: Send ptp4l_id from Proxy to Client once ptp4l is connected
intel-staging/libptpmgmt_iaclocklib pull request #19
Opened 2024-04-25 08:05 UTC by JunAnnLaiIntel

2024-04-26 02:25 UTC, yoongsiang2 commented on jclklib/client/connect_msg.cpp
> +#include <client/subscribe_msg.hpp>
why need to include subscribe msg header?

2024-04-29 04:23 UTC, AzuraTarmiziIntel requested changes

2024-04-29 04:23 UTC, AzuraTarmiziIntel commented on jclklib/proxy/connect.cpp
> +    while (system("ls /var/run/ptp4l*") != 0) {
For good code practice, do init the pe.ptp4l_id  to zero. 
Btw, i didnt see the pe structure being initialized to init values , before being used. 
Maybe we can have the init somewhere before  Connect in proxy started / or before this is used : ptp4l_event_loop

2024-04-29 04:27 UTC, AzuraTarmiziIntel commented
The changes are good. Just additional init i requested.

2024-04-29 05:20 UTC, AzuraTarmiziIntel commented on jclklib/proxy/connect.cpp
> +    while (system("ls /var/run/ptp4l*") != 0) {
JClkLibCommon::ptp_event pe = { 0, {0, 0, 0, 0, 0, 0, 0, 0}, 0 , 0 };

2024-04-29 10:19 UTC, AzuraTarmiziIntel approved these changes
LGTM. THanks for the changes

2024-04-29 10:22 UTC, merged