[WIP] Add notification message and process data
intel-staging/libptpmgmt_iaclocklib pull request #22
Opened 2024-05-02 06:17 UTC by JunAnnLaiIntel

Once client receive the notification message from proxy, it will process and write into client_ptp_data struct if there is changed.
The event count will also increment atomically when there is event changed.
![Uploading image.png…]()

2024-05-02 06:48 UTC, AzuraTarmiziIntel requested changes

2024-05-02 06:48 UTC, AzuraTarmiziIntel commented on jclklib/common/jclklib_import.hpp
Peter, this is now changed already. i think. can you rebase ?

2024-05-02 06:59 UTC, yoongsiang2 approved these changes

2024-05-02 07:24 UTC, JunAnnLaiIntel commented on jclklib/common/jclklib_import.hpp
Sure Azura, I already done the rebase.

2024-05-03 03:54 UTC, AzuraTarmiziIntel approved these changes

2024-05-03 03:57 UTC, merged