jclklib: Fix client terminate under high load condition
intel-staging/libptpmgmt_iaclocklib pull request #94
Opened 2024-06-25 05:57 UTC by JunAnnLaiIntel

Client will terminate intermittent when under stress test or high load condition due to the check_proxy_liveness() is not able to handle it properly.

2024-06-25 07:33 UTC, rupran commented
While this fixes the problem with logSyncInterval settings <= 0 and without the sleep() calls in the sample application, a client using the Clock Management API might also want to sleep for longer than one second between the `jcl_status_wait` calls and would then immediately receive timeouts even though the proxy is still alive.

Is this the expected behaviour or are there plans to allow arbitrary intervals between `jcl_status_wait` API calls in a generic way?

2024-07-01 07:35 UTC, yoongsiang2 commented
> While this fixes the problem with logSyncInterval settings <= 0 and without the sleep() calls in the sample application, a client using the Clock Management API might also want to sleep for longer than one second between the `jcl_status_wait` calls and would then immediately receive timeouts even though the proxy is still alive.
> 
> As an example, you could use the following settings:
> 
> * `logSyncInterval`: 2 in both ptp4l configurations (GM and slave)
> * start the sample application with `-i 2` (2 seconds of idle time)
> 
> This leads to an immediate timeout (`[jclklib][430847.137] Terminating: lost connection to jclklib Proxy`) after waking up from the `sleep()` call.
> 
> Is this the expected behaviour or are there plans to allow arbitrary intervals between `jcl_status_wait` API calls in a generic way?

Thank you for your feedback. Your concern is valid. We overlooked the possibility that users might set the clock synchronization interval to a very low value. We will discuss this and come up with a better design.

2024-07-04 08:44 UTC, yoongsiang2 requested changes

2024-07-04 08:44 UTC, yoongsiang2 commented on jclklib/client/jclk_client_state.hpp
> +        double timeout_second;
use "struct timespec" to reduce load in handling notification msg.

2024-07-04 08:44 UTC, yoongsiang2 commented on jclklib/client/jclk_client_state.hpp
> +        double timeout_second;
change name to last_notification_time

2024-07-04 08:44 UTC, yoongsiang2 commented on jclklib/client/jclk_client_state.hpp
> +        double get_proxy_liveness();
follow variable name: e.g. get/set_last_notification_time

2024-07-04 08:44 UTC, yoongsiang2 commented on jclklib/client/jclk_init.cpp
> +#define DEFAULT_LIVENESS_TIME_OUT 50  //50 msec
rename to DEFAULT_LIVENESS_TIMEOUT_IN_MS 50

2024-07-04 08:44 UTC, yoongsiang2 commented on jclklib/client/jclk_init.cpp
>      ClientConnectMessage *cmsg = dynamic_cast<decltype(cmsg)>(connectMsg.get());
more line 176 & 177 to 193

2024-07-04 08:44 UTC, yoongsiang2 commented on jclklib/client/jclk_init.cpp
> +        return -1;
remove return -1. if fail to check time, need to send msg to check liveness.

2024-07-04 08:44 UTC, yoongsiang2 commented on jclklib/client/jclk_init.cpp
> +    }
use else

2024-07-04 08:44 UTC, yoongsiang2 commented on jclklib/client/jclk_init.cpp
> +    struct timespec timeSpec;
rename to current_time

2024-07-04 08:44 UTC, yoongsiang2 commented on jclklib/client/jclk_init.cpp
> +        return true;
create a function with last_notification_time, current_time, and, timeout argument, and perform calculation inside.

2024-07-04 15:35 UTC, yoongsiang2 requested changes

2024-07-04 15:35 UTC, yoongsiang2 commented on jclklib/client/notification_msg.cpp
> +        currentClientState->set_last_notification_time(last_notification_time);
set the time only if clock_gettime() is successful, which mean that you need to put this line in "else"

2024-07-04 15:35 UTC, yoongsiang2 commented on jclklib/client/jclk_init.cpp
> +#define DEFAULT_LIVENESS_TIMEOUT_IN_MS 50  //50 msec
i think "50 ms" will be a better comment.

2024-07-04 15:35 UTC, yoongsiang2 commented on jclklib/client/jclk_init.cpp
> +    long long delta_in_ms = delta_in_sec * 1000LL + delta_in_nsec / 1000000LL;
suggest to use int64_t, instead of long long, to make sure same length is used in both 32bits and 64bits systems.

2024-07-05 01:36 UTC, yoongsiang2 approved these changes
LGTM. This patch improved the liveness check efficiency where it reduce the burden of message queue

2024-07-05 01:40 UTC, merged